---
name: Lint python cod
on:
  push:
    branches:
      - main
  #release:
  #  types: [published]

jobs:
  test:
    name: Run the tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
          pip install flask
          pip install isort
      - name: Run tests
        run: python app/tests.py
